#!/bin/bash

#******************************************************************************
# FILE: omp_bug4fix
# DESCRIPTION:
#   This script is used to set the thread stack size limit to accommodate
#   the omp_bug4 example. The example code requires @16MB per thread. For
#   safety, this script sets the stack limit to 20MB. Note that the way
#   to do this differs between architectures.
#*****************************************************************************/

# Set system stack (master thread stack size)
ulimit -s 30960

# Set OpenMP Stack (workers threads stack size)
OMP_STACKSIZE='20M'
export OMP_STACKSIZE

# Now call the executable - change the name to match yours
./omp_bug4
